version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: lifelessons-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lifelessons
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: lifelessons-redis
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Mailhog for email testing (optional)
  mailhog:
    image: mailhog/mailhog
    container_name: lifelessons-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    profiles:
      - mail

volumes:
  postgres_data:
  redis_data:
