# Nixpacks configuration for Railway
# This bypasses Docker Hub by using Nix packages directly

[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm-9_x']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'pnpm --filter api exec prisma generate --schema=../../prisma/schema.prisma',
  'pnpm --filter api build'
]

[start]
cmd = 'cd apps/api && prisma db push --schema=../../prisma/schema.prisma --accept-data-loss --skip-generate && node dist/main.js'
